import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { cookieName, validSession } from "@/lib/auth";

function base() { const value = process.env.WORDPRESS_API_URL; if (!value) throw new Error("WordPress is not configured yet."); return value.replace(/\/$/, ""); }
function headers() { const token = process.env.WORDPRESS_API_TOKEN || ""; return { "Content-Type": "application/json", Accept: "application/json", "X-Elroi-API-Token": token, Authorization: `Bearer ${token}` }; }
async function auth() { return validSession((await cookies()).get(cookieName)?.value); }
export async function GET() { try { const privateView = await auth(); const response = await fetch(`${base()}/videos${privateView ? "?admin=1" : ""}`, { headers: privateView ? headers() : undefined, cache: "no-store" }); const data = await response.json().catch(() => ({})); return NextResponse.json(data, { status: response.status }); } catch (error) { return NextResponse.json({ items: [], error: error instanceof Error ? error.message : "Videos could not be loaded." }, { status: 502 }); } }
export async function POST(request: Request) { if (!await auth()) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const response = await fetch(`${base()}/videos`, { method: "POST", headers: headers(), body: JSON.stringify(await request.json()), cache: "no-store" }); const data = await response.json().catch(() => ({})); return NextResponse.json(data, { status: response.status }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Video could not be saved." }, { status: 502 }); } }
export async function PATCH(request: Request) { if (!await auth()) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const body = await request.json(); const response = await fetch(`${base()}/videos/${encodeURIComponent(String(body.id))}`, { method: "PATCH", headers: headers(), body: JSON.stringify(body), cache: "no-store" }); const data = await response.json().catch(() => ({})); return NextResponse.json(data, { status: response.status }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Video could not be updated." }, { status: 502 }); } }
export async function DELETE(request: Request) { if (!await auth()) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const id = new URL(request.url).searchParams.get("id"); const response = await fetch(`${base()}/videos/${encodeURIComponent(id || "")}`, { method: "DELETE", headers: headers(), cache: "no-store" }); const data = await response.json().catch(() => ({})); return NextResponse.json(data, { status: response.status }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Video could not be deleted." }, { status: 502 }); } }
