"use client";
import { ChangeEvent, useEffect, useState } from "react";
import { AdPlacement, AdSettings } from "@/lib/types";

const placements = [
  ["homepage_banner", "Homepage banner", "970 × 250 px"], ["search_results", "Search results", "728 × 90 px"], ["hindi_category", "Hindi category", "728 × 90 px"], ["nepali_category", "Nepali category", "728 × 90 px"], ["english_category", "English category", "728 × 90 px"], ["song_page_top", "Song page top", "728 × 90 px"], ["song_page_bottom", "Song page bottom", "728 × 90 px"], ["desktop_sidebar", "Desktop sidebar", "300 × 600 px"], ["mobile_footer", "Mobile footer", "320 × 100 px"],
] as const;
const blankPlacement = (): AdPlacement => ({ enabled: false, code: "", imageUrl: "", imageAlt: "Advertisement", linkUrl: "", openNewTab: true });
const blankSettings = (): AdSettings => ({ global: false, placements: Object.fromEntries(placements.map(([key]) => [key, blankPlacement()])) });

function normalize(value: unknown): AdSettings { const raw = (value || {}) as Partial<AdSettings>; const old = (raw.placements || {}) as Record<string, unknown>; return { ...blankSettings(), ...raw, global: raw.global === true, placements: Object.fromEntries(placements.map(([key]) => { const item = old[key]; return [key, typeof item === "boolean" ? { ...blankPlacement(), enabled: item } : { ...blankPlacement(), ...((item || {}) as AdPlacement) }]; })) }; }
function readFile(event: ChangeEvent<HTMLInputElement>, callback: (value: string) => void) { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith("image/")) return; if (file.size > 8 * 1024 * 1024) return; const reader = new FileReader(); reader.onload = () => callback(String(reader.result || "")); reader.readAsDataURL(file); }

export function AdCenter() {
  const [logged, setLogged] = useState(false), [email, setEmail] = useState(""), [password, setPassword] = useState(""), [settings, setSettings] = useState<AdSettings>(blankSettings), [loading, setLoading] = useState(true), [saving, setSaving] = useState(false), [uploading, setUploading] = useState<string | null>(null), [error, setError] = useState(""), [saved, setSaved] = useState("");
  useEffect(() => { fetch("/api/admin/session").then((response) => response.json()).then((data) => { setLogged(data.authenticated); if (data.authenticated) fetch("/api/admin/ads").then((response) => response.json()).then((result) => setSettings(normalize(result.settings))).catch(() => setError("Could not load ad settings.")).finally(() => setLoading(false)); else setLoading(false); }).catch(() => setLoading(false)); }, []);
  async function login() { setError(""); const response = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!response.ok) return setError("Invalid email or password."); setLogged(true); const result = await fetch("/api/admin/ads").then((res) => res.json()); setSettings(normalize(result.settings)); }
  function update(key: string, value: Partial<AdPlacement>) { setSettings((current) => ({ ...current, placements: { ...current.placements, [key]: { ...blankPlacement(), ...current.placements[key], ...value } } })); setSaved(""); }
  async function save() { setSaving(true); setError(""); try { const response = await fetch("/api/admin/ads", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(settings) }); if (!response.ok) throw new Error("Ad settings could not be saved."); setSaved("All ad settings saved."); } catch (err) { setError(err instanceof Error ? err.message : "Ad settings could not be saved."); } finally { setSaving(false); } }
  async function upload(key: string, imageData: string) { setUploading(key); setError(""); try { const response = await fetch("/api/admin/ads/upload", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ imageData }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Banner upload failed."); update(key, { imageUrl: data.url, code: "" }); } catch (err) { setError(err instanceof Error ? err.message : "Banner upload failed."); } finally { setUploading(null); } }
  if (loading) return <div className="admin ads-center"><p className="muted">Loading ads center…</p></div>;
  if (!logged) return <div className="admin"><span className="eyebrow">Elroi Tunes / private</span><h1>Ads center</h1><div className="admin-card"><label>Email<input className="admin-input" value={email} onChange={(event) => setEmail(event.target.value)} type="email" /></label><label>Password<input className="admin-input" value={password} onChange={(event) => setPassword(event.target.value)} type="password" /></label><button className="admin-submit" onClick={login}>Sign in</button>{error && <p role="alert" className="error">{error}</p>}</div></div>;
  return <div className="admin ads-center"><header className="ads-center-header"><div><span className="eyebrow">Private admin</span><h1>Ads center</h1><p className="muted">Manage every ad placement, banner, and code block from one place.</p></div><button className={`ads-global-toggle ${settings.global ? "is-on" : ""}`} onClick={() => setSettings((current) => ({ ...current, global: !current.global }))}>{settings.global ? "Ads on" : "Ads off"}</button></header>{error && <p className="ads-error">{error}</p>}<section className="ads-guide"><strong>How it works</strong><span>Turn ads on globally, enable a placement, then add either custom HTML or upload a banner. Empty placements stay hidden.</span></section><div className="ads-placement-list">{placements.map(([key, label, size]) => { const item = settings.placements[key] || blankPlacement(); return <article className={`ads-placement ${item.enabled ? "is-enabled" : ""}`} key={key}><div className="ads-placement-top"><div><span className="ads-placement-label">{label}</span><span className="ads-placement-size">Recommended {size}</span></div><button className={`ads-placement-toggle ${item.enabled ? "is-on" : ""}`} onClick={() => update(key, { enabled: !item.enabled })}>{item.enabled ? "On" : "Off"}</button></div><div className="ads-placement-fields"><label>Ad code <span>HTML, script, or embed code</span><textarea rows={4} value={item.code || ""} onChange={(event) => update(key, { code: event.target.value, imageUrl: "" })} placeholder="Paste ad code here…" /></label><div className="ads-or">or upload a banner</div><label className="ads-file-label">Choose image<input type="file" accept="image/*" onChange={(event) => readFile(event, (image) => upload(key, image))} />{uploading === key && <span>Uploading…</span>}</label>{item.imageUrl && <div className="ads-preview"><img src={item.imageUrl} alt={item.imageAlt || "Ad preview"} /><button onClick={() => update(key, { imageUrl: "" })}>Remove</button></div>}<div className="ads-placement-row"><label>Banner link <input type="url" value={item.linkUrl || ""} onChange={(event) => update(key, { linkUrl: event.target.value })} placeholder="https://example.com" /></label><label>Alt text <input value={item.imageAlt || ""} onChange={(event) => update(key, { imageAlt: event.target.value })} /></label></div><label className="ads-checkbox"><input type="checkbox" checked={item.openNewTab !== false} onChange={(event) => update(key, { openNewTab: event.target.checked })} /> Open banner link in a new tab</label></div></article>; })}</div><div className="ads-save-bar"><span>{saved || "Changes are not live until you save."}</span><button className="admin-submit" onClick={save} disabled={saving}>{saving ? "Saving…" : "Save all ad settings"}</button></div></div>;
}
