"use client";

import Link from "next/link";
import { Bookmark, Check, ChevronLeft, ChevronRight, Heart, Info, Pause, Play, Search, Share2, Volume2, VolumeX, X } from "lucide-react";
import { useEffect, useMemo, useRef, useState } from "react";
import { clearOttGuest, readOttGuest, toggleOttList } from "@/lib/ott-guest";
import { Video, VideoCategory, VideoContentType } from "@/lib/types";

const names: Record<VideoContentType, string> = { message: "Message", worship: "Worship", testimony: "Real Story", prayer: "Prayer", devotional: "Devotional", "bible-story": "Scripture Story", "kids-family": "Kids & Family", "film-series": "Film & Series" };
const languages = { english: "English", nepali: "नेपाली", hindi: "हिन्दी" };
const title = (story: Video) => story.displayTitle || story.title;
const thumb = (story: Video) => story.thumbnailUrl || `https://i.ytimg.com/vi/${story.youtubeId}/hqdefault.jpg`;
const kind = (story: Video) => story.category?.name || (story.contentType ? names[story.contentType] : "Faith story");
const language = (story: Video) => languages[story.language || "english"];

function StoryCard({ story }: { story: Video }) {
  const [saved, setSaved] = useState(false);
  useEffect(() => { const refresh = () => setSaved(readOttGuest().list.some((item) => item.id === story.id)); refresh(); window.addEventListener("elroi-ott-guest", refresh); return () => window.removeEventListener("elroi-ott-guest", refresh); }, [story.id]);
  return <article className="ott-media-card"><Link href={`/ott/watch/${story.slug}`} className="ott-media-card-link"><div className="ott-media-image"><img src={thumb(story)} alt="" loading="lazy" /><span className="ott-play"><Play size={17} fill="currentColor" /></span>{story.isReel && <span className="ott-reel-badge">REEL</span>}</div><div className="ott-media-copy"><span>{kind(story)} · {language(story)}</span><h3>{title(story)}</h3><p>{story.channelName || "Elroi OTT"}</p></div></Link><button className="ott-card-save" type="button" onClick={() => setSaved(toggleOttList(story))} aria-label={`${saved ? "Remove" : "Save"} ${title(story)}`}>{saved ? <Check size={18} /> : <Bookmark size={18} />}</button></article>;
}
function Rail({ heading, stories, href, eyebrow = "EXPLORE THE COLLECTION" }: { heading: string; stories: Video[]; href: string; eyebrow?: string }) {
  if (!stories.length) return null;
  return <section className="ott-shelf" aria-label={heading}><div className="ott-shelf-head"><div><span className="ott-kicker">{eyebrow}</span><h2>{heading}</h2></div><Link href={href}>See all <span aria-hidden="true">→</span></Link></div><div className="ott-card-rail">{stories.slice(0, 12).map((story) => <StoryCard key={story.id} story={story} />)}</div></section>;
}
function Hero({ stories }: { stories: Video[] }) {
  const [index, setIndex] = useState(0), [paused, setPaused] = useState(false); const touch = useRef<number | null>(null);
  useEffect(() => setIndex(0), [stories]);
  useEffect(() => { if (stories.length < 2 || paused || window.matchMedia("(prefers-reduced-motion: reduce)").matches) return; const timer = window.setInterval(() => setIndex((current) => (current + 1) % stories.length), 7000); return () => window.clearInterval(timer); }, [stories.length, paused]);
  if (!stories.length) return <section className="ott-empty-hero"><div className="ott-empty-symbol" aria-hidden="true">✝</div><span className="ott-kicker">A NEW PLACE FOR HOPE</span><h1>Stories that stay with you.</h1><p>Worship, testimony, scripture, and hope are on their way to Elroi OTT. Come back soon for the first collection.</p></section>;
  const story = stories[index]; const go = (direction: number) => setIndex((current) => (current + direction + stories.length) % stories.length);
  return <section className="ott-hero" aria-roledescription="carousel" aria-label="Featured stories" tabIndex={0} onKeyDown={(event) => { if (event.key === "ArrowRight") go(1); if (event.key === "ArrowLeft") go(-1); }} onMouseEnter={() => setPaused(true)} onMouseLeave={() => setPaused(false)} onFocusCapture={() => setPaused(true)} onBlurCapture={(event) => { if (!event.currentTarget.contains(event.relatedTarget)) setPaused(false); }} onTouchStart={(event) => { touch.current = event.changedTouches[0]?.clientX ?? null; setPaused(true); }} onTouchEnd={(event) => { if (touch.current === null) return; const delta = (event.changedTouches[0]?.clientX || 0) - touch.current; if (Math.abs(delta) > 45) go(delta < 0 ? 1 : -1); touch.current = null; }}><img className="ott-hero-image" src={thumb(story)} alt="" fetchPriority="high" /><div className="ott-hero-shade" /><div className="ott-hero-copy"><span className="ott-kicker">FEATURED · {kind(story)} · {language(story)}</span><h1>{title(story)}</h1><p>{story.synopsis || story.description || "A story of faith, carefully chosen for you."}</p><small>{story.channelName || "Elroi OTT"}</small><div className="ott-hero-actions"><Link href={`/ott/watch/${story.slug}`} className="ott-watch-button"><Play size={18} fill="currentColor" /> Start watching</Link><Link href={`/ott/watch/${story.slug}`} className="ott-more-button"><Info size={18} /> More info</Link></div></div>{stories.length > 1 && <><button className="ott-hero-arrow ott-prev" type="button" onClick={() => go(-1)} aria-label="Previous featured story"><ChevronLeft /></button><button className="ott-hero-arrow ott-next" type="button" onClick={() => go(1)} aria-label="Next featured story"><ChevronRight /></button><div className="ott-hero-controls"><button type="button" onClick={() => setPaused(!paused)} aria-label={paused ? "Resume carousel" : "Pause carousel"}>{paused ? <Play size={17} /> : <Pause size={17} />}</button><span aria-live="polite">{index + 1} / {stories.length}</span><div className="ott-dots">{stories.map((item, position) => <button type="button" key={item.id} className={position === index ? "is-active" : ""} onClick={() => setIndex(position)} aria-label={`Show featured story ${position + 1}`} aria-current={position === index} />)}</div></div></>}</section>;
}
function Discover({ stories, categories, searchMode }: { stories: Video[]; categories: VideoCategory[]; searchMode: boolean }) {
  const [query, setQuery] = useState(""), [category, setCategory] = useState(""), [languageFilter, setLanguageFilter] = useState(""), [type, setType] = useState(""); const input = useRef<HTMLInputElement>(null);
  useEffect(() => { const params = new URLSearchParams(window.location.search); setQuery(params.get("q") || ""); setCategory(params.get("category") || ""); setType(params.get("type") || ""); if (searchMode) input.current?.focus(); }, [searchMode]);
  const filtered = useMemo(() => stories.filter((story) => { const text = `${title(story)} ${story.title} ${story.synopsis || ""} ${story.description || ""} ${story.channelName || ""} ${(story.topics || []).join(" ")} ${story.category?.name || ""}`.toLocaleLowerCase(); return (!query || text.includes(query.toLocaleLowerCase())) && (!category || story.category?.slug === category) && (!languageFilter || story.language === languageFilter) && (!type || story.contentType === type); }), [stories, query, category, languageFilter, type]);
  const selected = categories.find((item) => item.slug === category);
  return <div className={searchMode ? "ott-discovery ott-search-view" : "ott-discovery"}><div className="ott-discovery-head"><span className="ott-kicker">{searchMode ? "SEARCH ELROI OTT" : "THE COLLECTION"}</span><h1>{searchMode ? "Find your next story." : selected?.name || "Explore stories of faith."}</h1><p>{searchMode ? "Search across English, Nepali, and Hindi stories." : "Worship, messages, testimonies, and moments of hope."}</p></div>{searchMode && <div className="ott-search-panel"><label className="ott-search-field"><Search size={23} aria-hidden="true" /><input ref={input} type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search stories, people, prayer, hope…" aria-label="Search OTT stories" /></label><div className="ott-search-options"><label>Language<select value={languageFilter} onChange={(event) => setLanguageFilter(event.target.value)}><option value="">All languages</option>{Object.entries(languages).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Category<select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">All categories</option>{categories.map((item) => <option key={item.id} value={item.slug}>{item.name}</option>)}</select></label><label>Story type<select value={type} onChange={(event) => setType(event.target.value)}><option value="">All types</option>{Object.entries(names).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label></div>{(query || category || languageFilter || type) && <button className="ott-clear-filters" type="button" onClick={() => { setQuery(""); setCategory(""); setLanguageFilter(""); setType(""); input.current?.focus(); }}>Clear search and filters</button>}</div>}{!searchMode && !category && !type && categories.some((item) => stories.some((story) => story.category?.slug === item.slug)) ? categories.map((item) => <Rail key={item.id} heading={item.name} href={`/ott/explore?category=${encodeURIComponent(item.slug)}`} stories={stories.filter((story) => story.category?.slug === item.slug && !story.isReel)} />) : <><p className="ott-results-count">{filtered.length} {filtered.length === 1 ? "story" : "stories"}</p>{filtered.length ? <div className="ott-results-grid">{filtered.map((story) => <StoryCard key={story.id} story={story} />)}</div> : <div className="ott-no-results"><Search size={30} /><h2>{stories.length ? "No matching stories" : "The collection opens soon"}</h2><p>{stories.length ? "Try another search, language, or category." : "Our first stories are being prepared. Come back soon."}</p>{stories.length > 0 && <Link href="/ott/search">Search all stories</Link>}</div>}</>}</div>;
}
function Reel({ story }: { story: Video }) {
  const frame = useRef<HTMLIFrameElement>(null); const [muted, setMuted] = useState(true);
  useEffect(() => { const element = frame.current; if (!element) return; const observer = new IntersectionObserver(([entry]) => { element.contentWindow?.postMessage(JSON.stringify({ event: "command", func: entry.isIntersecting ? "playVideo" : "pauseVideo", args: [] }), "https://www.youtube-nocookie.com"); }, { threshold: 0.72 }); observer.observe(element); return () => observer.disconnect(); }, []);
  const toggleSound = () => { frame.current?.contentWindow?.postMessage(JSON.stringify({ event: "command", func: muted ? "unMute" : "mute", args: [] }), "https://www.youtube-nocookie.com"); setMuted(!muted); };
  const share = async () => { const url = `${window.location.origin}/ott/watch/${story.slug}`; if (navigator.share) await navigator.share({ title: title(story), url }); else await navigator.clipboard?.writeText(url); };
  return <article className="ott-reel"><iframe ref={frame} src={`https://www.youtube-nocookie.com/embed/${story.youtubeId}?rel=0&modestbranding=1&playsinline=1&enablejsapi=1&autoplay=1&mute=1`} title={title(story)} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen /><div><span>ELROI REEL · {language(story)}</span><h2>{title(story)}</h2><p>{story.channelName || "Elroi OTT"}</p><div className="ott-reel-actions"><button type="button" onClick={toggleSound} aria-label={muted ? "Turn sound on" : "Mute"}>{muted ? <VolumeX size={18} /> : <Volume2 size={18} />}</button><button type="button" onClick={() => void share()}><Share2 size={18} /> Share</button><Link href={`/ott/watch/${story.slug}`}>Open story</Link></div></div></article>;
}
export function OttExperience({ videos, categories, mode = "home" }: { videos: Video[]; categories: VideoCategory[]; mode?: "home" | "explore" | "search" | "reels" | "my-list" }) {
  const [more, setMore] = useState(false), [guestTick, setGuestTick] = useState(0); const closeButton = useRef<HTMLButtonElement>(null);
  useEffect(() => { const refresh = () => setGuestTick((value) => value + 1); const open = () => setMore(true); window.addEventListener("elroi-ott-guest", refresh); window.addEventListener("elroi-ott-more", open); return () => { window.removeEventListener("elroi-ott-guest", refresh); window.removeEventListener("elroi-ott-more", open); }; }, []);
  useEffect(() => { if (!more) return; closeButton.current?.focus(); const onKey = (event: KeyboardEvent) => { if (event.key === "Escape") setMore(false); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [more]);
  const guest = useMemo(() => readOttGuest(), [guestTick]); const listed = videos.filter((story) => guest.list.some((item) => item.id === story.id)); const continued = guest.history.map((entry) => videos.find((story) => story.id === entry.id)).filter((story): story is Video => Boolean(story));
  const sheet = more && <div className="ott-sheet-backdrop" onMouseDown={() => setMore(false)}><aside className="ott-more-sheet" role="dialog" aria-modal="true" aria-label="More Elroi OTT options" onMouseDown={(event) => event.stopPropagation()}><button ref={closeButton} className="ott-sheet-close" type="button" onClick={() => setMore(false)} aria-label="Close menu"><X /></button><span className="ott-kicker">ELROI OTT</span><h2>Your journey</h2><Link href="/">Return to Elroi Lyrics</Link><button type="button" onClick={() => { clearOttGuest(); setMore(false); }}>Clear local journey data</button><p>New stories of faith, across English, Nepali, and Hindi.</p></aside></div>;
  if (mode === "explore" || mode === "search") return <main className="ott-page ott-subpage"><Discover stories={videos} categories={categories} searchMode={mode === "search"} />{sheet}</main>;
  if (mode === "reels") { const reels = videos.filter((story) => story.isReel); return <main className="ott-page ott-reels-page"><header><span className="ott-kicker">ELROI REELS</span><h1>Small moments. Lasting hope.</h1><p>Stay a while. Find a word for today.</p></header>{reels.length ? <div className="ott-reels-feed">{reels.map((story) => <Reel key={story.id} story={story} />)}</div> : <div className="ott-no-results"><Heart size={30} /><h2>Moments of hope are coming soon.</h2><p>The first Reels are being prepared.</p><Link href="/ott">Return home</Link></div>}{sheet}</main>; }
  if (mode === "my-list") return <main className="ott-page ott-subpage ott-my-list"><span className="ott-kicker">YOUR COLLECTION</span><h1>My List</h1>{listed.length ? <div className="ott-results-grid">{listed.map((story) => <StoryCard key={story.id} story={story} />)}</div> : <div className="ott-no-results"><Bookmark size={30} /><h2>A space for stories you love.</h2><p>Save a story and it will be waiting here.</p><Link href="/ott/explore">Explore stories</Link></div>}{sheet}</main>;
  const longForm = videos.filter((story) => !story.isReel); const featured = longForm.filter((story) => story.featured).sort((a, b) => (a.heroRank || 999) - (b.heroRank || 999)); const heroStories = [...featured, ...longForm.filter((story) => !story.featured).sort((a, b) => Date.parse(b.publishedAt || "") - Date.parse(a.publishedAt || ""))].slice(0, 10);
  return <main className="ott-page"><Hero stories={heroStories} />{longForm.length > 0 && <div className="ott-home-content">{continued.length > 0 && <Rail heading="Continue watching" href="/ott/my-list" stories={continued} eyebrow="PICK UP WHERE YOU LEFT OFF" />}{listed.length > 0 && <Rail heading="My List" href="/ott/my-list" stories={listed} eyebrow="SAVED FOR YOU" />}{categories.map((category) => <Rail key={category.id} heading={category.name} href={`/ott/explore?category=${encodeURIComponent(category.slug)}`} stories={longForm.filter((story) => story.category?.slug === category.slug).sort((a, b) => (a.shelfRank || 999) - (b.shelfRank || 999))} />)}{!categories.some((category) => longForm.some((story) => story.category?.slug === category.slug)) && <Rail heading="Stories of faith" href="/ott/explore" stories={longForm} />}</div>}{sheet}</main>;
}
