"use client";

import Link from "next/link";
import { ArrowLeft, Bookmark, Check, Play, Share2 } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { readOttGuest, recordOttProgress, toggleOttList } from "@/lib/ott-guest";
import { Video } from "@/lib/types";

const storyTitle = (story: Video) => story.displayTitle || story.title;
const storyLabel = (story: Video) => story.isReel ? "Elroi Reel" : story.contentType ? story.contentType.replace(/-/g, " ") : story.category?.name || "Faith journey";
function Card({ story }: { story: Video }) { return <Link href={`/ott/watch/${story.slug}`} className="ott-media-card"><div className="ott-media-image"><img src={story.thumbnailUrl || `https://i.ytimg.com/vi/${story.youtubeId}/hqdefault.jpg`} alt="" loading="lazy" /><span className="ott-play"><Play size={15} fill="currentColor" /></span></div><div className="ott-media-copy"><span>{storyLabel(story)}</span><h3>{storyTitle(story)}</h3><p>{story.channelName || "Elroi Christian content"}</p></div></Link>; }

export function OttWatch({ video, related }: { video: Video; related: Video[] }) {
  const frame = useRef<HTMLIFrameElement>(null); const [saved, setSaved] = useState(false); const [progress, setProgress] = useState(0);
  useEffect(() => { setSaved(readOttGuest().list.some((item) => item.id === video.id)); const savedProgress = readOttGuest().history.find((item) => item.id === video.id)?.progress || 0; setProgress(savedProgress); }, [video.id]);
  useEffect(() => {
    const receive = (event: MessageEvent) => { if (event.origin !== "https://www.youtube-nocookie.com") return; try { const data = typeof event.data === "string" ? JSON.parse(event.data) : event.data; const current = data?.info?.currentTime; const duration = data?.info?.duration; if (typeof current === "number" && current > 5) { setProgress(Math.floor(current)); recordOttProgress(video, current, typeof duration === "number" ? duration : 0); } } catch {} };
    window.addEventListener("message", receive); const ticker = window.setInterval(() => frame.current?.contentWindow?.postMessage(JSON.stringify({ event: "command", func: "getCurrentTime", args: [] }), "https://www.youtube-nocookie.com"), 15000); return () => { window.removeEventListener("message", receive); window.clearInterval(ticker); };
  }, [video]);
  const share = async () => { const url = window.location.href; if (navigator.share) await navigator.share({ title: storyTitle(video), url }); else await navigator.clipboard?.writeText(url); };
  const unavailable = video.embeddable === false || video.sourceHealth === "unavailable";
  return <main className="ott-page ott-watch-page"><Link href="/ott" className="ott-back"><ArrowLeft size={16} /> Back to Elroi OTT</Link>{unavailable ? <section className="ott-player-unavailable"><span className="ott-kicker">STORY UNAVAILABLE</span><h1>This story is taking a pause.</h1><p>The source is no longer available for embedded playback. Explore another moment of hope below.</p><Link href="/ott/explore">Explore stories</Link></section> : <div className="ott-player"><iframe ref={frame} src={`https://www.youtube-nocookie.com/embed/${video.youtubeId}?rel=0&modestbranding=1&playsinline=1&enablejsapi=1`} title={storyTitle(video)} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" /></div>}<section className="ott-watch-copy"><span className="ott-kicker">{storyLabel(video)} · {video.language || "english"}</span><h1>{storyTitle(video)}</h1><p className="ott-source">From {video.channelName || "Elroi Christian content"}</p><p>{video.synopsis || video.description || "A faith-filled story curated for your journey."}</p>{progress > 5 && <p className="ott-resume-note">Your journey resumes from {Math.floor(progress / 60)}:{String(progress % 60).padStart(2, "0")}.</p>}<div className="ott-watch-actions"><button type="button" onClick={() => setSaved(toggleOttList(video))}>{saved ? <Check size={17} /> : <Bookmark size={17} />}{saved ? "Saved to My List" : "Save to My List"}</button><button type="button" onClick={() => void share()}><Share2 size={17} /> Share</button></div>{video.topics?.length ? <div className="ott-topics">{video.topics.map((topic) => <span key={topic}>{topic}</span>)}</div> : null}</section>{related.length ? <section className="ott-shelf"><div><span className="ott-kicker">CONTINUE THE JOURNEY</span><h2>More for your faith</h2></div><div className="ott-card-rail">{related.map((story) => <Card key={story.id} story={story} />)}</div></section> : null}</main>;
}
