import Link from "next/link";
import { ArrowLeft, Play } from "lucide-react";
import { Video } from "@/lib/types";

function title(video: Video) { return video.displayTitle || video.title; }
function label(video: Video) { return video.isReel ? "Elroi Reel" : video.contentType ? video.contentType.replace(/-/g, " ") : video.category?.name || "Faith journey"; }
function Card({ video }: { video: Video }) { return <Link href={`/ott/watch/${video.slug}`} className="ott-media-card"><div className="ott-media-image"><img src={video.thumbnailUrl || `https://img.youtube.com/vi/${video.youtubeId}/hqdefault.jpg`} alt="" loading="lazy" /><span className="ott-play"><Play size={15} fill="currentColor" /></span></div><div className="ott-media-copy"><span>{label(video)}</span><h3>{title(video)}</h3><p>{video.channelName || "Elroi Christian content"}</p></div></Link>; }
export function OttWatch({ video, related }: { video: Video; related: Video[] }) {
  return <main className="ott-page ott-watch-page"><Link href="/ott" className="ott-back"><ArrowLeft size={16} /> Back to Elroi OTT</Link><div className="ott-player"><iframe src={`https://www.youtube-nocookie.com/embed/${video.youtubeId}?rel=0&modestbranding=1`} title={title(video)} allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowFullScreen referrerPolicy="strict-origin-when-cross-origin" /></div><section className="ott-watch-copy"><span className="ott-kicker">{label(video)} · {video.language || "english"}</span><h1>{title(video)}</h1><p className="ott-source">From {video.channelName || "Elroi Christian content"}</p><p>{video.synopsis || video.description || "A faith-filled story curated for your journey."}</p>{video.topics?.length ? <div className="ott-topics">{video.topics.map((topic) => <span key={topic}>{topic}</span>)}</div> : null}<a href={video.youtubeUrl} className="ott-youtube-link" target="_blank" rel="noreferrer"><Play size={18} fill="currentColor" /> Watch on YouTube</a></section>{related.length ? <section className="ott-shelf"><div><span className="ott-kicker">CONTINUE THE JOURNEY</span><h2>More for your faith</h2></div><div className="ott-card-rail">{related.map((item) => <Card key={item.id} video={item} />)}</div></section> : null}</main>;
}
