"use client";

import { useMemo, useState } from "react";
import { CheckCircle2, Plus, X } from "lucide-react";
import { LyricSection } from "@/lib/types";
import { UploadSong } from "@/lib/upload";
import { normalizeLyricText } from "@/lib/lyrics";

const blank: UploadSong = { title: "", romanTitle: "", alternateTitles: [], romanAlternateTitles: [], language: "hindi", artist: "", worshipTeam: "", composer: "", lyricist: "", album: "", releaseYear: "", songKey: "", tempo: "", youtubeUrl: "", audioUrl: "", excerpt: "", lastReviewedAt: "", genres: [], categories: [], themes: [], occasions: [], slug: "", lyrics: [], seo: { title: "", description: "" } };
const choices = { genres: ["Worship", "Praise", "Gospel", "Contemporary", "Hymn"], categories: ["Worship", "Praise", "Prayer", "Christmas", "Easter"], themes: ["Jesus", "Faith", "Grace", "Hope", "Holy Spirit", "Salvation"], occasions: ["Sunday Service", "Prayer Meeting", "Christmas", "Easter", "Communion"] } as const;

function parseLyrics(original: string, roman: string): LyricSection[] {
  const parse = (value: string) => {
    const rows: { label: string; text: string }[] = []; let label = "Lyrics"; let lines: string[] = [];
    const flush = () => { const text = lines.join("\n").trim(); if (text) rows.push({ label, text }); lines = []; };
    normalizeLyricText(value).split("\n").forEach((line) => { const tag = line.trim().match(/^\[([^\]\n]+)\]$/); if (tag) { flush(); label = tag[1].trim() || "Lyrics"; } else lines.push(line); }); flush(); return rows;
  };
  const native = parse(original), romanRows = parse(roman);
  return Array.from({ length: Math.max(native.length, romanRows.length) }, (_, index) => ({ label: native[index]?.label || romanRows[index]?.label || `Section ${index + 1}`, original: native[index]?.text || "", roman: romanRows[index]?.text || "" })).filter((section) => section.original || section.roman);
}
function splitTitles(value: string) { return value.split(",").map((item) => item.trim()).filter(Boolean); }
function nativeLabel(language: UploadSong["language"]) { return language === "english" ? "English lyrics" : language === "nepali" ? "Nepali lyrics" : "Hindi lyrics"; }

function ChoiceButtons({ value, onChange }: { value: UploadSong["language"] | "publish" | "draft"; onChange: (value: never) => void }) {
  const items = value === "publish" || value === "draft" ? [["publish", "Publish now"], ["draft", "Save draft"]] : [["hindi", "Hindi"], ["english", "English"], ["nepali", "Nepali"]];
  return <div className="choice-buttons">{items.map(([key, label]) => <button key={key} type="button" className={value === key ? "is-selected" : ""} onClick={() => onChange(key as never)}>{label}</button>)}</div>;
}
function TagChoices({ label, values, onChange, presets }: { label: string; values: string[]; onChange: (values: string[]) => void; presets: readonly string[] }) {
  const [custom, setCustom] = useState(""); const toggle = (item: string) => onChange(values.includes(item) ? values.filter((value) => value !== item) : [...values, item]); const add = () => { const item = custom.trim(); if (item && !values.includes(item)) onChange([...values, item]); setCustom(""); };
  return <div className="tag-group"><span className="field-name">{label}</span><div className="tag-buttons">{presets.map((item) => <button type="button" key={item} className={values.includes(item) ? "is-selected" : ""} onClick={() => toggle(item)}>{item}</button>)}{values.filter((item) => !presets.includes(item as never)).map((item) => <button type="button" key={item} className="is-selected custom-tag" onClick={() => toggle(item)}>{item}<X size={13} /></button>)}</div><div className="custom-tag-input"><input value={custom} onChange={(event) => setCustom(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") { event.preventDefault(); add(); } }} placeholder={`Add ${label.toLowerCase()}`} /><button type="button" aria-label={`Add ${label.toLowerCase()}`} onClick={add}><Plus size={16} /></button></div></div>;
}

export function UploadPortal() {
  const [song, setSong] = useState<UploadSong>(blank), [nativeLyrics, setNativeLyrics] = useState(""), [romanLyrics, setRomanLyrics] = useState(""), [busy, setBusy] = useState(false), [message, setMessage] = useState<{ ok: boolean; text: string } | null>(null);
  const sections = useMemo(() => parseLyrics(nativeLyrics, romanLyrics), [nativeLyrics, romanLyrics]);
  const update = <K extends keyof UploadSong>(field: K, value: UploadSong[K]) => setSong((current) => ({ ...current, [field]: value }));
  async function publish(status: "publish" | "draft") { setBusy(true); setMessage(null); try { const response = await fetch("/api/upload/publish", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...song, lyrics: sections, status }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "WordPress could not publish this song."); setMessage({ ok: true, text: status === "draft" ? "Draft saved in WordPress." : `Published successfully: ${data.url || data.slug || "song is live"}.` }); } catch (error) { setMessage({ ok: false, text: error instanceof Error ? error.message : "Could not publish the song." }); } finally { setBusy(false); } }
  return <main className="upload-page manual-upload"><header className="upload-header"><div><span className="eyebrow">ELROI TUNES / PUBLISHING</span><h1>Publish a song</h1><p>Paste final lyrics, choose the essentials, and publish directly to WordPress.</p></div><button className="upload-logout" onClick={async () => { await fetch("/api/admin/logout", { method: "POST" }); window.location.reload(); }}>Sign out</button></header>{message && <div className={`upload-message ${message.ok ? "success" : "failure"}`} role="status">{message.ok && <CheckCircle2 size={18} />}{message.text}</div>}
    <section className="manual-layout"><div className="manual-main">
      <section className="card form-card"><span className="eyebrow">01 / SONG</span><div className="field-grid"><label>Song title *<input value={song.title} onChange={(event) => update("title", event.target.value)} placeholder="e.g. Tumsa Koi Nahi" /></label><label>Roman title<input value={song.romanTitle || ""} onChange={(event) => update("romanTitle", event.target.value)} placeholder="Roman / Hinglish title" /></label><label>Artist / singer *<input value={song.artist} onChange={(event) => update("artist", event.target.value)} placeholder="Artist or worship team" /></label><label>Worship team<input value={song.worshipTeam || ""} onChange={(event) => update("worshipTeam", event.target.value)} placeholder="Optional" /></label></div><label>Language *<ChoiceButtons value={song.language} onChange={(value) => update("language", value)} /></label><label>URL slug <span className="optional">optional — WordPress can create it from the title</span><input value={song.slug} onChange={(event) => update("slug", event.target.value)} placeholder="tumsa-koi-nahi" /></label></section>
      <section className="card form-card lyrics-paste"><span className="eyebrow">02 / LYRICS</span><p className="form-hint">Use tags like <code>[Verse 1]</code>, <code>[Chorus]</code> and <code>[Bridge]</code>. They are kept and highlighted on the song page.</p><div className="lyrics-paste-grid"><label>{nativeLabel(song.language)} *<textarea rows={15} value={nativeLyrics} onChange={(event) => setNativeLyrics(event.target.value)} placeholder={'[Verse 1]\nPaste final lyrics here…'} /></label>{song.language !== "english" && <label>Roman lyrics <span className="optional">optional</span><textarea rows={15} value={romanLyrics} onChange={(event) => setRomanLyrics(event.target.value)} placeholder={'[Verse 1]\nPaste matching Roman / Hinglish lyrics here…'} /></label>}</div><p className="section-count">{sections.length ? `${sections.length} lyric section${sections.length === 1 ? "" : "s"} ready` : "Add lyrics to create sections"}</p></section>
      <section className="card form-card"><span className="eyebrow">03 / DISCOVERABILITY</span><TagChoices label="Genres" values={song.genres || []} onChange={(values) => update("genres", values)} presets={choices.genres} /><TagChoices label="Categories" values={song.categories || []} onChange={(values) => update("categories", values)} presets={choices.categories} /><TagChoices label="Themes" values={song.themes || []} onChange={(values) => update("themes", values)} presets={choices.themes} /><TagChoices label="Occasions" values={song.occasions || []} onChange={(values) => update("occasions", values)} presets={choices.occasions} /></section>
    </div><aside className="manual-side"><section className="card form-card"><span className="eyebrow">DETAILS</span><div className="compact-fields"><label>Composer<input value={song.composer || ""} onChange={(event) => update("composer", event.target.value)} /></label><label>Lyricist<input value={song.lyricist || ""} onChange={(event) => update("lyricist", event.target.value)} /></label><label>Album<input value={song.album || ""} onChange={(event) => update("album", event.target.value)} /></label><label>Release year<input inputMode="numeric" value={song.releaseYear || ""} onChange={(event) => update("releaseYear", event.target.value)} /></label><label>Song key<input value={song.songKey || ""} onChange={(event) => update("songKey", event.target.value)} placeholder="e.g. G" /></label><label>Tempo (BPM)<input inputMode="numeric" value={song.tempo || ""} onChange={(event) => update("tempo", event.target.value)} /></label></div><label>YouTube / YouTube Music URL<input type="url" value={song.youtubeUrl || ""} onChange={(event) => update("youtubeUrl", event.target.value)} /></label><label>Audio URL<input type="url" value={song.audioUrl || ""} onChange={(event) => update("audioUrl", event.target.value)} /></label></section><section className="card form-card"><span className="eyebrow">SEARCH & NOTES</span><label>Alternate titles <span className="optional">separate with commas</span><input value={(song.alternateTitles || []).join(", ")} onChange={(event) => update("alternateTitles", splitTitles(event.target.value))} /></label><label>Roman alternate titles <span className="optional">separate with commas</span><input value={(song.romanAlternateTitles || []).join(", ")} onChange={(event) => update("romanAlternateTitles", splitTitles(event.target.value))} /></label><label>Short description<textarea rows={3} value={song.excerpt || ""} onChange={(event) => update("excerpt", event.target.value)} /></label><label>SEO title<input value={song.seo?.title || ""} onChange={(event) => update("seo", { ...song.seo, title: event.target.value })} /></label><label>SEO description<textarea rows={3} value={song.seo?.description || ""} onChange={(event) => update("seo", { ...song.seo, description: event.target.value })} /></label><label>Last reviewed<input type="date" value={song.lastReviewedAt || ""} onChange={(event) => update("lastReviewedAt", event.target.value)} /></label></section></aside></section>
    <footer className="upload-footer publish-dock"><div><strong>Ready to send to WordPress?</strong><p>Publishing creates or updates the matching slug and refreshes the main app.</p></div><div className="publish-actions"><button className="secondary-button" onClick={() => publish("draft")} disabled={busy || !song.title || !song.artist || !sections.length}>Save draft</button><button className="publish-button" onClick={() => publish("publish")} disabled={busy || !song.title || !song.artist || !sections.length}>{busy ? "Publishing…" : "Publish to WordPress"}</button></div></footer>
  </main>;
}
