import { cookies } from "next/headers";
import { NextResponse } from "next/server";
import { cookieName, validSession } from "@/lib/auth";

function tokenHeaders() { const token = process.env.WORDPRESS_API_TOKEN; if (!token) throw new Error("WordPress publishing is not configured yet."); return { "Content-Type": "application/json", Accept: "application/json", "X-Elroi-API-Token": token, Authorization: `Bearer ${token}` }; }
function apiBase() { const base = process.env.WORDPRESS_API_URL; if (!base) throw new Error("WordPress is not configured yet."); return base.replace(/\/$/, ""); }
function publisherBase() { return process.env.WORDPRESS_PUBLISH_URL?.replace(/\/$/, "") || `${apiBase().replace(/\/wp-json\/lyrics\/v1$/, "")}/wp-json/elroi-publisher/v1`; }
async function auth() { return validSession((await cookies()).get(cookieName)?.value); }

export async function GET() { if (!await auth()) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const response = await fetch(`${apiBase()}/songs?per_page=100`, { cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || "Songs could not be loaded."); return NextResponse.json(data, { headers: { "Cache-Control": "no-store" } }); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Songs could not be loaded." }, { status: 502 }); } }
export async function PATCH(request: Request) { if (!await auth()) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const body = await request.json(); const response = await fetch(`${publisherBase()}/songs/${encodeURIComponent(String(body.id))}`, { method: "PATCH", headers: tokenHeaders(), body: JSON.stringify(body), cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || data.error || "Song could not be updated."); return NextResponse.json(data); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Song could not be updated." }, { status: 502 }); } }
export async function DELETE(request: Request) { if (!await auth()) return NextResponse.json({ error: "Unauthorized" }, { status: 401 }); try { const id = new URL(request.url).searchParams.get("id"); if (!id) return NextResponse.json({ error: "Song id is required." }, { status: 400 }); const response = await fetch(`${publisherBase()}/songs/${encodeURIComponent(id)}`, { method: "DELETE", headers: tokenHeaders(), cache: "no-store" }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || data.error || "Song could not be deleted."); return NextResponse.json(data); } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Song could not be deleted." }, { status: 502 }); } }
