<?php
/**
 * Plugin Name: Christian Lyrics API
 * Description: Song content model, normalized REST API, validation, ad settings, search and revalidation hooks for SongLight.
 * Version: 0.1.0
 */
if (!defined('ABSPATH')) exit;
final class Christian_Lyrics_API {
  public function __construct() { add_action('init', [$this,'register_song']); add_action('rest_api_init', [$this,'routes']); add_action('save_post_song', [$this,'revalidate'], 20, 3); add_filter('wp_insert_post_data', [$this,'validate'], 10, 2); register_activation_hook(__FILE__, [$this,'activate']); }
  public function register_song() { register_post_type('song', ['label'=>'Songs','public'=>true,'show_in_rest'=>true,'supports'=>['title','editor','excerpt','thumbnail'],'rewrite'=>['slug'=>'songs']]); foreach(['artist','genre','worship_category','theme','language','occasion','scripture_reference'] as $tax) register_taxonomy($tax,'song',['label'=>ucwords(str_replace('_',' ',$tax)),'public'=>true,'show_in_rest'=>true,'hierarchical'=>in_array($tax,['genre','worship_category','theme','occasion'])]); foreach(['roman_title','alternate_titles','roman_alternate_titles','artist','worship_team','lyrics','seo_title','seo_description'] as $key) register_post_meta('song',$key,['single'=>true,'type'=>'string','show_in_rest'=>true,'auth_callback'=>function(){return current_user_can('edit_posts');}]); }
  public function routes() { register_rest_route('lyrics/v1','/songs', ['methods'=>'GET','callback'=>[$this,'songs'],'permission_callback'=>'__return_true']); register_rest_route('lyrics/v1','/songs/(?P<slug>[\w-]+)', ['methods'=>'GET','callback'=>[$this,'song'],'permission_callback'=>'__return_true']); register_rest_route('lyrics/v1','/suggestions', ['methods'=>'GET','callback'=>[$this,'suggestions'],'permission_callback'=>'__return_true']); register_rest_route('lyrics/v1','/search', ['methods'=>'GET','callback'=>[$this,'search'],'permission_callback'=>'__return_true']); register_rest_route('lyrics/v1','/settings/ads', ['methods'=>['GET','PUT'],'callback'=>[$this,'ads'],'permission_callback'=>function($r){return $r->get_method()==='GET'||current_user_can('manage_options');}]); }
  private function normalize($post) { return ['id'=>$post->ID,'slug'=>$post->post_name,'title'=>get_the_title($post),'romanTitle'=>get_post_meta($post->ID,'roman_title',true),'alternateTitles'=>json_decode(get_post_meta($post->ID,'alternate_titles',true) ?: '[]',true),'romanAlternateTitles'=>json_decode(get_post_meta($post->ID,'roman_alternate_titles',true) ?: '[]',true),'language'=>get_post_meta($post->ID,'language',true) ?: 'english','artist'=>get_post_meta($post->ID,'artist',true) ?: get_post_meta($post->ID,'worship_team',true) ?: '','lyrics'=>json_decode(get_post_meta($post->ID,'lyrics',true) ?: '[]',true),'seo'=>['title'=>get_post_meta($post->ID,'seo_title',true),'description'=>get_post_meta($post->ID,'seo_description',true)],'updatedAt'=>$post->post_modified_gmt]; }
  public function songs($request) { $page=max(1,(int)$request->get_param('page')); $args=['post_type'=>'song','post_status'=>'publish','posts_per_page'=>min(50,max(1,(int)($request->get_param('per_page')?:20))),'paged'=>$page,'orderby'=>'modified','order'=>'DESC']; if($request->get_param('language')) { $args['meta_query']=[['key'=>'language','value'=>sanitize_key($request->get_param('language'))]]; } $query=new WP_Query($args); return rest_ensure_response(['items'=>array_map([$this,'normalize'],$query->posts),'total'=>(int)$query->found_posts,'page'=>$page]); }
  public function song($request) { $posts=get_posts(['post_type'=>'song','name'=>sanitize_title($request['slug']),'post_status'=>'publish','numberposts'=>1]); return $posts ? rest_ensure_response($this->normalize($posts[0])) : new WP_Error('not_found','Song not found',['status'=>404]); }
  private function fold($value) { $value=remove_accents(wp_strip_all_tags((string)$value)); $value=mb_strtolower($value); $value=preg_replace('/[\x{2019}\x{27}]/u','',$value); $value=preg_replace('/[^\p{L}\p{N}]+/u',' ', $value); return trim(preg_replace('/\s+/',' ',$value)); }
  private function variants($value) { $value=$this->fold($value); return array_unique([$value,str_replace('aa','a',$value),str_replace('sh','s',$value),str_replace('ee','i',$value),str_replace('oo','u',$value)]); }
  private function song_match($song,$query) { $q=$this->fold($query); if(!$q) return null; $roman=$this->variants($query); $title=$this->fold($song['title']); $roman_title=$this->variants($song['romanTitle']); $alts=array_merge((array)$song['alternateTitles'],(array)$song['romanAlternateTitles']); $alt_variants=[]; foreach($alts as $alt) $alt_variants=array_merge($alt_variants,$this->variants($alt)); $artist=$this->fold($song['artist']); $native_lyrics=$this->fold(implode(' ',array_map(function($line){return $line['original']??'';},$song['lyrics']))); $roman_lyrics=$this->fold(implode(' ',array_map(function($line){return $line['roman']??'';},$song['lyrics']))); if($title===$q||strpos($title,$q)!==false) return ['type'=>'title','score'=>100,'snippet'=>'']; foreach(array_merge($roman_title,$alt_variants) as $value) if($value===$q||strpos($value,$q)!==false) return ['type'=>'roman_title','score'=>90,'snippet'=>'']; if($artist&&strpos($artist,$q)!==false) return ['type'=>'artist','score'=>70,'snippet'=>'']; if(strpos($native_lyrics,$q)!==false) return ['type'=>'lyrics','score'=>50,'snippet'=>$this->snippet($native_lyrics,$q)]; foreach($roman as $value) if($value&&strpos($roman_lyrics,$value)!==false) return ['type'=>'roman_lyrics','score'=>40,'snippet'=>$this->snippet($roman_lyrics,$value)]; return null; }
  private function snippet($text,$query) { $text=preg_replace('/\s+/',' ',trim($text)); $pos=mb_stripos($text,$query); if($pos===false) return mb_substr($text,0,110).(mb_strlen($text)>110?'…':''); $start=max(0,$pos-35); $out=mb_substr($text,$start,mb_strlen($query)+70); return ($start?'…':'').$out.(($start+mb_strlen($out))<mb_strlen($text)?'…':''); }
  private function matching_posts($request) { $query=sanitize_text_field($request->get_param('q') ?: ''); $args=['post_type'=>'song','post_status'=>'publish','posts_per_page'=>-1,'no_found_rows'=>true]; $language=sanitize_key($request->get_param('language') ?: ''); if($language) $args['meta_query']=[['key'=>'language','value'=>$language]]; $posts=(new WP_Query($args))->posts; $matches=[]; foreach($posts as $post) { $song=$this->normalize($post); $match=$this->song_match($song,$query); if($match) $matches[]=array_merge($song,['matchType'=>$match['type'],'snippet'=>$match['snippet'],'_score'=>$match['score']]); } usort($matches,function($a,$b){return $b['_score']<=>$a['_score'];}); return $matches; }
  public function suggestions($request) { $q=mb_substr(sanitize_text_field($request->get_param('q') ?: ''),0,120); if(mb_strlen($q)<2) return rest_ensure_response(['items'=>[]]); $items=array_slice($this->matching_posts($request),0,6); return rest_ensure_response(['items'=>array_map(function($song){return ['id'=>$song['id'],'slug'=>$song['slug'],'title'=>$song['title'],'romanTitle'=>$song['romanTitle'],'artist'=>$song['artist'],'language'=>$song['language'],'matchType'=>$song['matchType'],'snippet'=>$song['snippet']];},$items)]); }
  public function search($request) { $q=mb_substr(sanitize_text_field($request->get_param('q') ?: ''),0,120); if(!$q) return rest_ensure_response(['items'=>[],'total'=>0,'page'=>1]); $all=$this->matching_posts($request); $page=max(1,(int)($request->get_param('page')?:1)); $per_page=min(50,max(1,(int)($request->get_param('per_page')?:20))); $items=array_slice($all,($page-1)*$per_page,$per_page); foreach($items as &$item) unset($item['_score']); return rest_ensure_response(['items'=>$items,'total'=>count($all),'page'=>$page,'per_page'=>$per_page]); }
  public function ads($request) { if($request->get_method()==='PUT') { $value=$request->get_json_params(); update_option('christian_lyrics_ads',is_array($value)?$value:[]); } return rest_ensure_response(get_option('christian_lyrics_ads',['global'=>false,'placements'=>[]])); }
  public function activate() { global $wpdb; $table=$wpdb->prefix.'postmeta'; $wpdb->query("ALTER TABLE {$table} ADD FULLTEXT lyrics_search (meta_key, meta_value)"); flush_rewrite_rules(); }
  public function validate($data,$postarr) { if(($postarr['post_type']??'')==='song' && ($postarr['post_status']??'')==='publish' && empty($postarr['post_title'])) $data['post_status']='draft'; return $data; }
  public function revalidate($post_id,$post,$update) { if(wp_is_post_revision($post_id)||wp_is_post_autosave($post_id)) return; $url=getenv('VERCEL_REVALIDATE_URL') ?: getenv('SONGLIGHT_REVALIDATE_URL'); $secret=getenv('WORDPRESS_WEBHOOK_SECRET') ?: getenv('SONGLIGHT_REVALIDATE_SECRET'); if(!$url||!$secret) return; wp_remote_post($url,['timeout'=>5,'blocking'=>false,'headers'=>['Content-Type'=>'application/json','X-Webhook-Secret'=>$secret],'body'=>wp_json_encode(['slug'=>$post->post_name,'status'=>$post->post_status,'language'=>get_post_meta($post_id,'language',true)])]); }
}
new Christian_Lyrics_API();
