<?php
/**
 * Plugin Name: Christian Lyrics API
 * Description: Easy song publishing, automatic Hindi/Nepali Roman transliteration, normalized lyrics REST API, search, ads and revalidation.
 * Version: 0.2.0
 */
if (!defined('ABSPATH')) exit;

final class Christian_Lyrics_API {
  private $meta = ['roman_title','alternate_titles','roman_alternate_titles','artist','worship_team','composer','lyricist','album','release_year','song_key','tempo','youtube_url','audio_url','excerpt','lyrics','seo_title','seo_description','last_reviewed_at','language'];
  public function __construct() {
    add_action('init', [$this,'register_song']);
    add_action('rest_api_init', [$this,'routes']);
    add_action('add_meta_boxes', [$this,'meta_box']);
    add_action('add_meta_boxes', [$this,'task_meta_box']);
    add_action('admin_menu', [$this,'settings_menu']);
    add_action('admin_init', [$this,'register_settings']);
    add_action('admin_enqueue_scripts', [$this,'admin_assets']);
    add_action('wp_ajax_cla_transliterate', [$this,'ajax_transliterate']);
    add_action('save_post_song', [$this,'save_meta'], 10, 2);
    add_action('save_post_song', [$this,'revalidate'], 20, 3);
    add_action('save_post_song_task', [$this,'save_task_meta'], 10, 2);
    add_filter('wp_insert_post_data', [$this,'validate'], 10, 2);
    register_activation_hook(__FILE__, [$this,'activate']);
  }
  public function register_song() {
    register_post_type('song', ['label'=>'Songs','public'=>true,'show_in_rest'=>true,'supports'=>['title','editor','excerpt','thumbnail'],'rewrite'=>['slug'=>'songs']]);
    register_post_type('song_task', ['label'=>'Song Tasks','public'=>false,'show_ui'=>true,'show_in_menu'=>'edit.php?post_type=song','supports'=>['title'],'capability_type'=>'post','map_meta_cap'=>true]);
    foreach(['artist','genre','worship_category','theme','language','occasion','scripture_reference','tag'] as $tax) register_taxonomy($tax,'song',['label'=>ucwords(str_replace('_',' ',$tax)),'public'=>true,'show_in_rest'=>true,'hierarchical'=>in_array($tax,['genre','worship_category','theme','occasion'],true)]);
    foreach($this->meta as $key) register_post_meta('song',$key,['single'=>true,'type'=>'string','show_in_rest'=>true,'auth_callback'=>function(){return current_user_can('edit_posts');}]);
    foreach(['task_language','task_status','task_priority','task_notes','task_created_at','task_updated_at','task_uploaded_song_id','task_uploaded_song_slug','task_uploaded_at'] as $key) register_post_meta('song_task',$key,['single'=>true,'type'=>'string','show_in_rest'=>false,'auth_callback'=>function(){return current_user_can('edit_posts');}]);
  }
  public function admin_assets($hook) {
    if (!in_array($hook,['post.php','post-new.php'],true) || get_current_screen()->post_type !== 'song') return;
    wp_register_script('cla-admin', '', [], '0.2.0', true); wp_enqueue_script('cla-admin'); wp_add_inline_script('cla-admin', $this->admin_script());
    wp_register_style('cla-admin-style', false, [], '0.2.0'); wp_enqueue_style('cla-admin-style'); wp_add_inline_style('cla-admin-style', $this->admin_style());
  }
  public function routes() {
    register_rest_route('lyrics/v1','/songs', ['methods'=>'GET','callback'=>[$this,'songs'],'permission_callback'=>'__return_true']);
    register_rest_route('lyrics/v1','/songs/(?P<slug>[\w-]+)', ['methods'=>'GET','callback'=>[$this,'song'],'permission_callback'=>'__return_true']);
    register_rest_route('lyrics/v1','/suggestions', ['methods'=>'GET','callback'=>[$this,'suggestions'],'permission_callback'=>'__return_true']);
    register_rest_route('lyrics/v1','/search', ['methods'=>'GET','callback'=>[$this,'search'],'permission_callback'=>'__return_true']);
    register_rest_route('lyrics/v1','/settings/ads', ['methods'=>['GET','PUT'],'callback'=>[$this,'ads'],'permission_callback'=>function($r){return $r->get_method()==='GET'||current_user_can('manage_options');}]);
    register_rest_route('lyrics/v1','/tasks', ['methods'=>'GET','callback'=>[$this,'tasks'],'permission_callback'=>[$this,'task_permission']]);
    register_rest_route('lyrics/v1','/tasks', ['methods'=>'POST','callback'=>[$this,'create_task'],'permission_callback'=>[$this,'task_permission']]);
    register_rest_route('lyrics/v1','/tasks/(?P<id>\d+)', ['methods'=>'PATCH','callback'=>[$this,'update_task'],'permission_callback'=>[$this,'task_permission']]);
    register_rest_route('lyrics/v1','/tasks/(?P<id>\d+)', ['methods'=>'DELETE','callback'=>[$this,'delete_task'],'permission_callback'=>[$this,'task_permission']]);
  }
  public function meta_box() { add_meta_box('christian_lyrics_song_details','Create your song — Elroi Tunes',[$this,'render_meta_box'],'song','normal','high'); }
  public function render_meta_box($post) {
    wp_nonce_field('christian_lyrics_song_details','christian_lyrics_nonce');
    echo '<input type="hidden" id="cla_ajax_nonce" value="'.esc_attr(wp_create_nonce('cla_transliterate')).'">';
    $get=function($key)use($post){return get_post_meta($post->ID,$key,true);}; $language=$get('language')?:'hindi'; $stored_lyrics=json_decode($get('lyrics')?:'[]',true); if(!is_array($stored_lyrics))$stored_lyrics=[]; $format_lyrics=function($key,$roman=false)use($stored_lyrics){$rows=[];foreach($stored_lyrics as $row){if(!is_array($row))continue;$text=(string)($row[$key]??'');if(!$text&&$key==='original')$text=(string)($row['text']??'');$text=$this->clean_legacy($text,$roman);$label=trim((string)($row['label']??''));if($text!=='')$rows[]=($label?'['.$label."]\n":'').$text;}return implode("\n\n",$rows);}; $original_lyrics=$format_lyrics('original'); $roman_lyrics=$format_lyrics('roman',true);
    echo '<div class="cla-editor"><div class="cla-welcome"><strong>Paste once. We do the rest.</strong><span>Choose a language, paste your lyrics, and Elroi Tunes will create the missing script, sections, search fields and SEO helpers automatically.</span></div>';
    echo '<div class="cla-grid"><div><label class="cla-label" for="cla_song_title">Song title</label><input class="cla-big-input" id="cla_song_title" name="cla_song_title" value="'.esc_attr(get_the_title($post)).'" placeholder="e.g. Yeshu Tera Naam"></div><div><label class="cla-label" for="cla_language">Language</label><select class="cla-big-input" id="cla_language" name="cla_language"><option value="hindi" '.selected($language,'hindi',false).'>Hindi / हिन्दी</option><option value="nepali" '.selected($language,'nepali',false).'>Nepali / नेपाली</option><option value="english" '.selected($language,'english',false).'>English</option></select></div></div>';
    echo '<div class="cla-grid"><div><label class="cla-label" for="cla_artist">Artist / singer <span>(optional)</span></label><input class="cla-big-input" id="cla_artist" name="cla_artist" value="'.esc_attr($get('artist')).'" placeholder="e.g. Elroi Worship"></div><div><label class="cla-label" for="cla_worship_team">Worship team <span>(optional)</span></label><input class="cla-big-input" id="cla_worship_team" name="cla_worship_team" value="'.esc_attr($get('worship_team')).'" placeholder="e.g. Elroi Worship Team"></div></div>';
    echo '<div class="cla-script-grid"><div><label class="cla-label" for="cla_original_lyrics"><span id="cla-original-label">'.($language==='english'?'Lyrics':'Hindi / Nepali lyrics').'</span></label><textarea class="cla-lyrics-input" id="cla_original_lyrics" name="cla_original_lyrics" rows="14" placeholder="Paste the lyrics here...&#10;&#10;You may separate verses with blank lines.">'.esc_textarea($original_lyrics).'</textarea></div><div><label class="cla-label" for="cla_roman_lyrics"><span id="cla-roman-label">'.($language==='hindi'?'Hinglish Roman lyrics':($language==='nepali'?'Roman Nepali lyrics':'Lyrics')).'</span> <span>(optional for Hindi/Nepali)</span></label><textarea class="cla-lyrics-input" id="cla_roman_lyrics" name="cla_roman_lyrics" rows="14" placeholder="Optional — paste the Roman version if you have it.">'.esc_textarea($roman_lyrics).'</textarea></div></div>';
    echo '<div class="cla-actions"><button type="button" class="button button-primary button-large" id="cla_generate">Generate missing version</button><span id="cla_generate_status" class="cla-status">For Hindi/Nepali, the empty side will be generated automatically when you save.</span></div>';
    echo '<details class="cla-advanced"><summary>More song details <span>optional</span></summary><div class="cla-advanced-grid">';
    foreach(['composer'=>'Composer','lyricist'=>'Lyricist','album'=>'Album','release_year'=>'Release year','song_key'=>'Song key','tempo'=>'Tempo (BPM)','youtube_url'=>'YouTube / YouTube Music URL','audio_url'=>'Audio URL','excerpt'=>'Short description','seo_title'=>'SEO title','seo_description'=>'SEO description','last_reviewed_at'=>'Last reviewed date'] as $key=>$label){$value=$get($key);$large=in_array($key,['excerpt','seo_description'],true);echo '<div class="cla-field '.($large?'cla-wide':'').'"><label class="cla-label" for="cla_'.$key.'">'.$label.'</label>'.($large?'<textarea class="cla-big-input" rows="3" id="cla_'.$key.'" name="cla_'.$key.'">'.esc_textarea($value).'</textarea>':'<input class="cla-big-input" type="text" id="cla_'.$key.'" name="cla_'.$key.'" value="'.esc_attr($value).'">').'</div>';}
    echo '</div></details><div class="cla-hidden"><input type="hidden" id="cla_lyrics" name="cla_lyrics" value="'.esc_attr($get('lyrics')).'"><input type="hidden" id="cla_roman_title" name="cla_roman_title" value="'.esc_attr($get('roman_title')).'"><input type="hidden" id="cla_alternate_titles" name="cla_alternate_titles" value="'.esc_attr($get('alternate_titles')).'"><input type="hidden" id="cla_roman_alternate_titles" name="cla_roman_alternate_titles" value="'.esc_attr($get('roman_alternate_titles')).'"></div></div>';
  }
  public function save_meta($post_id,$post) {
    if(!isset($_POST['christian_lyrics_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['christian_lyrics_nonce'])),'christian_lyrics_song_details')||defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE||!current_user_can('edit_post',$post_id)||$post->post_type!=='song')return;
    $lang=sanitize_key(wp_unslash($_POST['cla_language']??'hindi'));if(!in_array($lang,['hindi','nepali','english'],true))$lang='hindi';$title=sanitize_text_field(wp_unslash($_POST['cla_song_title']??''));
    if($title&&$title!==$post->post_title){remove_action('save_post_song',[$this,'save_meta'],10);wp_update_post(['ID'=>$post_id,'post_title'=>$title,'post_name'=>sanitize_title($title)]);add_action('save_post_song',[$this,'save_meta'],10,2);}
    $original=sanitize_textarea_field(wp_unslash($_POST['cla_original_lyrics']??''));$roman=sanitize_textarea_field(wp_unslash($_POST['cla_roman_lyrics']??''));
    if($lang==='english')$sections=$this->sections_bracketed($original,'');else{if(!$original&&$roman)$original=$this->google_transliterate($roman,$lang);if(!$roman&&$original)$roman=$this->native_to_roman($original);$sections=$this->sections_bracketed($original,$roman);}
    $values=['language'=>$lang,'artist'=>sanitize_text_field(wp_unslash($_POST['cla_artist']??'')),'worship_team'=>sanitize_text_field(wp_unslash($_POST['cla_worship_team']??'')),'lyrics'=>wp_json_encode($sections,JSON_UNESCAPED_UNICODE),'roman_title'=>sanitize_text_field(wp_unslash($_POST['cla_roman_title']??''))];
    if(!$values['roman_title']&&$lang!=='english')$values['roman_title']=$this->native_to_roman($title);
    foreach(['composer','lyricist','album','release_year','song_key','tempo','youtube_url','audio_url','excerpt','seo_title','seo_description','last_reviewed_at']as$key)$values[$key]=sanitize_textarea_field(wp_unslash($_POST['cla_'.$key]??''));
    if(!$values['seo_title'])$values['seo_title']=$title.' Lyrics'.($lang==='hindi'?' in Hindi and Hinglish':($lang==='nepali'?' in Nepali and Roman':' in English'));if(!$values['seo_description'])$values['seo_description']='Read '.$title.' lyrics in '.$lang.' on Elroi Tunes.';
    $values['alternate_titles']=wp_json_encode(array_filter([$title]),JSON_UNESCAPED_UNICODE);$values['roman_alternate_titles']=wp_json_encode(array_filter([$values['roman_title']]),JSON_UNESCAPED_UNICODE);foreach($values as$key=>$value)update_post_meta($post_id,$key,$value);
  }
  private function sections($original,$roman){$split=function($text){$text=trim((string)$text);if(!$text)return[];$names='verse|chorus|bridge|ending|refrain|intro|outro|वर्स|वार्स|कोरस|ब्रिज|एंडिंग|रिफ्रेन|इंट्रो|आउट्रो';$parts=preg_split('/\R\s*(?=(?:'.$names.')(?:\s+\d+)?\s*:?[ \t]*$)/imu',$text);$out=[];foreach($parts as$part){$lines=preg_split('/\R/',$part);$label='';if($lines&&preg_match('/^\s*('.$names.')(?:\s+\d+)?\s*:?[ \t]*$/iu',trim($lines[0]),$m)){$raw=mb_strtolower($m[1]);$label=preg_match('/verse|वर्स|वार्स/u',$raw)?'Verse':(preg_match('/chorus|कोरस/u',$raw)?'Chorus':(preg_match('/bridge|ब्रिज/u',$raw)?'Bridge':(preg_match('/ending|एंडिंग/u',$raw)?'Ending':(preg_match('/refrain|रिफ्रेन/u',$raw)?'Refrain':(preg_match('/intro|इंट्रो/u',$raw)?'Intro':'Outro')))));if(preg_match('/\d+/',trim($lines[0]),$num))$label.=' '.$num[0];array_shift($lines);}$out[]=['label'=>$label,'text'=>trim(implode("\n",$lines))];}return$out;};$a=$split($original);$b=$split($roman);$out=[];foreach($a as$i=>$row)$out[]=['label'=>$row['label']?:$this->section_label($i),'original'=>$row['text'],'roman'=>$b[$i]['text']??''];return$out;}
  private function sections_bracketed($original,$roman){$split=function($text){$text=$this->clean_legacy((string)$text);if(!$text)return[];$text=preg_replace('/(?<!^)(?<!\R)\s*(?=\[[^\]\r\n]+\])/u',"\n",trim($text));$lines=preg_split('/\R/',$text);$out=[];$label='';$body=[];$flush=function()use(&$out,&$label,&$body){$value=trim(implode("\n",$body));if($value!==''||$label!=='')$out[]=['label'=>$label,'text'=>$value];$label='';$body=[];};foreach($lines as$line){if(preg_match('/^\s*\[([^\]\r\n]+)\]\s*$/u',$line,$m)){$flush();$label=trim($m[1]);}else$body[]=$line;}$flush();return$out;};$a=$split($original);$b=$split($roman);$out=[];$count=max(count($a),count($b));for($i=0;$i<$count;$i++)$out[]=['label'=>$a[$i]['label']??$b[$i]['label']??'Section '.($i+1),'original'=>$a[$i]['text']??'','roman'=>$b[$i]['text']??''];return array_values(array_filter($out,function($row){return $row['original']!==''||$row['roman']!=='';}));}
  private function section_label($i){return ['Verse 1','Chorus','Verse 2','Bridge','Ending'][$i]??'Section '.($i+1);}
  private function fold($value){$value=remove_accents(wp_strip_all_tags((string)$value));$value=mb_strtolower($value);$value=preg_replace('/[\x{2019}\x{27}]/u','',$value);$value=preg_replace('/[^\p{L}\p{N}]+/u',' ',$value);return trim(preg_replace('/\s+/',' ',$value));}
  private function variants($value){$value=$this->fold($value);return array_unique([$value,str_replace('aa','a',$value),str_replace('sh','s',$value),str_replace('ee','i',$value),str_replace('oo','u',$value)]);}
  private function romanize_word($word){$cons=['क'=>'k','ख'=>'kh','ग'=>'g','घ'=>'gh','ङ'=>'n','च'=>'ch','छ'=>'chh','ज'=>'j','झ'=>'jh','ञ'=>'n','ट'=>'t','ठ'=>'th','ड'=>'d','ढ'=>'dh','ण'=>'n','त'=>'t','थ'=>'th','द'=>'d','ध'=>'dh','न'=>'n','प'=>'p','फ'=>'ph','ब'=>'b','भ'=>'bh','म'=>'m','य'=>'y','र'=>'r','ल'=>'l','व'=>'v','श'=>'sh','ष'=>'sh','स'=>'s','ह'=>'h','क़'=>'q','ख़'=>'kh','ग़'=>'gh','ज़'=>'z','ड़'=>'r','ढ़'=>'rh'];$vowels=['अ'=>'a','आ'=>'aa','इ'=>'i','ई'=>'ee','उ'=>'u','ऊ'=>'oo','ए'=>'e','ऐ'=>'ai','ओ'=>'o','औ'=>'au'];$matras=['ा'=>'aa','ि'=>'i','ी'=>'ee','ु'=>'u','ू'=>'oo','ृ'=>'ri','े'=>'e','ै'=>'ai','ो'=>'o','ौ'=>'au'];$chars=preg_split('//u',(string)$word,-1,PREG_SPLIT_NO_EMPTY);$out='';for($i=0;$i<count($chars);$i++){$c=$chars[$i];if(isset($cons[$c])){$out.=$cons[$c];$next=$chars[$i+1]??'';if($next==='्'){$i++;continue;}if(isset($matras[$next])){$out.=$matras[$next];$i++;}else{$out.='a';}}elseif(isset($vowels[$c]))$out.=$vowels[$c];elseif($c==='ं'||$c==='ँ')$out.='n';elseif($c==='ः')$out.='h';elseif($c==='़'){}else$out.=$c;}return preg_replace('/a$/','',$out);}
  private function native_to_roman($text){$out='';foreach(preg_split('/(\R)/',(string)$text,-1,PREG_SPLIT_DELIM_CAPTURE)as$line){if(preg_match('/^\R$/',$line)){$out.=$line;continue;}$trim=trim($line);if(preg_match('/^\s*(?:वर्स|वार्स|कोरस|ब्रिज|एंडिंग|रिफ्रेन|इंट्रो|आउट्रो|verse|chorus|bridge|ending|refrain|intro|outro)(?:\s+\d+)?\s*[:：]?\s*$/iu',$trim,$m)){$heading=$trim;if(preg_match('/(?:वर्स|वार्स|verse)/iu',$trim))$heading='Verse';elseif(preg_match('/(?:कोरस|chorus)/iu',$trim))$heading='Chorus';elseif(preg_match('/(?:ब्रिज|bridge)/iu',$trim))$heading='Bridge';elseif(preg_match('/(?:एंडिंग|ending)/iu',$trim))$heading='Ending';elseif(preg_match('/(?:रिफ्रेन|refrain)/iu',$trim))$heading='Refrain';elseif(preg_match('/(?:इंट्रो|intro)/iu',$trim))$heading='Intro';elseif(preg_match('/(?:आउट्रो|outro)/iu',$trim))$heading='Outro';if(preg_match('/\d+/', $trim,$num))$heading.=' '.$num[0];$out.=$heading.':';continue;}foreach(preg_split('/(\s+)/',$line,-1,PREG_SPLIT_DELIM_CAPTURE)as$part)$out.=preg_match('/^\s+$/',$part)?$part:$this->romanize_word($part); }return trim($out);}
  private function roman_to_native($text){$map=['chh'=>'छ','ksh'=>'क्ष','sh'=>'श','th'=>'थ','dh'=>'ध','kh'=>'ख','gh'=>'घ','bh'=>'भ','ph'=>'फ','aa'=>'आ','ee'=>'ई','ii'=>'ई','oo'=>'ऊ','ou'=>'ऊ','ai'=>'ऐ','au'=>'औ','a'=>'अ','i'=>'इ','u'=>'उ','e'=>'ए','o'=>'ओ','k'=>'क','g'=>'ग','c'=>'क','j'=>'ज','t'=>'त','d'=>'द','n'=>'न','p'=>'प','b'=>'ब','m'=>'म','y'=>'य','r'=>'र','l'=>'ल','v'=>'व','w'=>'व','s'=>'स','h'=>'ह','f'=>'फ'];$out='';foreach(preg_split('/(\R)/',$text,-1,PREG_SPLIT_DELIM_CAPTURE)as$line){if(preg_match('/^\R$/',$line)){$out.=$line;continue;}foreach(preg_split('/(\s+)/',$line,-1,PREG_SPLIT_DELIM_CAPTURE)as$word){if(preg_match('/^\s+$/',$word)){$out.=$word;continue;}$x=mb_strtolower($word);$converted='';while($x!==''){$hit=false;foreach($map as$key=>$val)if(strpos($x,$key)===0){$converted.=$val;$x=substr($x,strlen($key));$hit=true;break;}if(!$hit){$converted.=mb_substr($x,0,1);$x=mb_substr($x,1);}}$out.=$converted;}}return$out;}
  private function google_transliterate($text,$lang){$itc=$lang==='nepali'?'ne-t-i0-und':'hi-t-i0-und';$lines=preg_split('/(\R)/',$text,-1,PREG_SPLIT_DELIM_CAPTURE);$out='';foreach($lines as$line){if(preg_match('/^\R$/',$line)||trim($line)===''){$out.=$line;continue;}if(preg_match('/^\s*(verse|chorus|bridge|ending|refrain|intro|outro)(?:\s+\d+)?\s*:?[ \t]*$/iu',$line)){$out.=$line;continue;}$chunks=preg_split('/([,;:!?।]+)/u',$line,-1,PREG_SPLIT_DELIM_CAPTURE);foreach($chunks as$chunk){if($chunk===''||preg_match('/^[,;:!?।]+$/u',$chunk)){$out.=$chunk;continue;}$url='https://inputtools.google.com/request?'.http_build_query(['text'=>$chunk,'itc'=>$itc,'num'=>1,'cp'=>0,'cs'=>1,'ie'=>'utf-8','oe'=>'utf-8','app'=>'elroi-tunes']);$response=wp_remote_get($url,['timeout'=>8,'headers'=>['Accept'=>'application/json']]);$converted='';if(!is_wp_error($response)&&wp_remote_retrieve_response_code($response)===200){$data=json_decode(wp_remote_retrieve_body($response),true);if(!empty($data[1])&&is_array($data[1])){$pieces=[];foreach($data[1]as$group)$pieces[]=$group[1][0]??$group[0]??'';$converted=implode('',$pieces);}}$out.=($converted?:$this->roman_to_native($chunk));}}return$out;}
  public function ajax_transliterate(){check_ajax_referer('cla_transliterate','nonce');if(!current_user_can('edit_posts'))wp_send_json_error(['message'=>'Not allowed'],403);$text=sanitize_textarea_field(wp_unslash($_POST['text']??''));$lang=sanitize_key(wp_unslash($_POST['language']??'hindi'));$direction=sanitize_key(wp_unslash($_POST['direction']??'to_native'));if(!$text||!in_array($lang,['hindi','nepali'],true))wp_send_json_error(['message'=>'Missing lyrics']);$converted=$direction==='to_roman'?$this->native_to_roman($text):$this->google_transliterate($text,$lang);wp_send_json_success(['text'=>$converted]);}
  private function clean_legacy($text,$roman=false){$text=class_exists('Normalizer')?(normalizer_normalize((string)$text,Normalizer::FORM_C)?:((string)$text)):(string)$text;$text=preg_replace('/\\r\\n|\\n|\\r/',"\n",$text);$text=str_replace(["\r\n","\r"],"\n",$text);$text=str_replace("�",'',$text);$text=preg_replace('/n(?=\s*\[[^\]\r\n]+\])/u',"\n",$text);return class_exists('Normalizer')?(normalizer_normalize($text,Normalizer::FORM_C)?:$text):$text;}
  private function normalize($post){$lyrics=json_decode(get_post_meta($post->ID,'lyrics',true)?:'[]',true);if(!is_array($lyrics))$lyrics=[];foreach($lyrics as&$line){$line['original']=$this->clean_legacy($line['original']??'');$line['roman']=$this->clean_legacy($line['roman']??'',true);}return['id'=>$post->ID,'slug'=>$post->post_name,'title'=>get_the_title($post),'romanTitle'=>get_post_meta($post->ID,'roman_title',true),'alternateTitles'=>json_decode(get_post_meta($post->ID,'alternate_titles',true)?:'[]',true),'romanAlternateTitles'=>json_decode(get_post_meta($post->ID,'roman_alternate_titles',true)?:'[]',true),'language'=>get_post_meta($post->ID,'language',true)?:'english','artist'=>get_post_meta($post->ID,'artist',true)?:get_post_meta($post->ID,'worship_team',true)?:'','composer'=>get_post_meta($post->ID,'composer',true),'lyricist'=>get_post_meta($post->ID,'lyricist',true),'album'=>get_post_meta($post->ID,'album',true),'releaseYear'=>get_post_meta($post->ID,'release_year',true),'songKey'=>get_post_meta($post->ID,'song_key',true),'tempo'=>get_post_meta($post->ID,'tempo',true),'lyrics'=>$lyrics,'genres'=>wp_get_object_terms($post->ID,'genre',['fields'=>'names']),'categories'=>wp_get_object_terms($post->ID,'worship_category',['fields'=>'names']),'themes'=>wp_get_object_terms($post->ID,'theme',['fields'=>'names']),'occasions'=>wp_get_object_terms($post->ID,'occasion',['fields'=>'names']),'youtubeUrl'=>get_post_meta($post->ID,'youtube_url',true),'audioUrl'=>get_post_meta($post->ID,'audio_url',true),'seo'=>['title'=>get_post_meta($post->ID,'seo_title',true),'description'=>get_post_meta($post->ID,'seo_description',true)],'updatedAt'=>$post->post_modified_gmt];}
  private function song_match($song,$query){$q=$this->fold($query);if(!$q)return null;$roman=$this->variants($query);$title=$this->fold($song['title']);$rt=$this->variants($song['romanTitle']);$alts=[];foreach(array_merge((array)$song['alternateTitles'],(array)$song['romanAlternateTitles'])as$alt)$alts=array_merge($alts,$this->variants($alt));$artist=$this->fold($song['artist']);$native=$this->fold(implode(' ',array_column($song['lyrics'],'original')));$rl=$this->fold(implode(' ',array_column($song['lyrics'],'roman')));if($title===$q||strpos($title,$q)!==false)return['type'=>'title','score'=>100,'snippet'=>''];foreach(array_merge($rt,$alts)as$v)if($v&&($v===$q||strpos($v,$q)!==false))return['type'=>'roman_title','score'=>90,'snippet'=>''];if($artist&&strpos($artist,$q)!==false)return['type'=>'artist','score'=>70,'snippet'=>''];if(strpos($native,$q)!==false)return['type'=>'lyrics','score'=>50,'snippet'=>$this->snippet($native,$q)];foreach($roman as$v)if($v&&strpos($rl,$v)!==false)return['type'=>'roman_lyrics','score'=>40,'snippet'=>$this->snippet($rl,$v)];return null;}
  private function snippet($text,$q){$text=preg_replace('/\s+/',' ',trim($text));$p=mb_stripos($text,$q);if($p===false)return mb_substr($text,0,110).(mb_strlen($text)>110?'…':'');$s=max(0,$p-35);$o=mb_substr($text,$s,mb_strlen($q)+70);return($s?'…':'').$o.(($s+mb_strlen($o))<mb_strlen($text)?'…':'');}
  private function matching_posts($r){$q=sanitize_text_field($r->get_param('q')?:'');$args=['post_type'=>'song','post_status'=>'publish','posts_per_page'=>-1,'no_found_rows'=>true];$lang=sanitize_key($r->get_param('language')?:'');if($lang)$args['meta_query']=[['key'=>'language','value'=>$lang]];$matches=[];foreach((new WP_Query($args))->posts as$post){$song=$this->normalize($post);$m=$this->song_match($song,$q);if($m)$matches[]=array_merge($song,['matchType'=>$m['type'],'snippet'=>$m['snippet'],'_score'=>$m['score']]);}usort($matches,function($a,$b){return$b['_score']<=>$a['_score'];});return$matches;}
  public function songs($r){$page=max(1,(int)$r->get_param('page'));$args=['post_type'=>'song','post_status'=>'publish','posts_per_page'=>min(50,max(1,(int)($r->get_param('per_page')?:20))),'paged'=>$page,'orderby'=>'modified','order'=>'DESC'];if($r->get_param('language'))$args['meta_query']=[['key'=>'language','value'=>sanitize_key($r->get_param('language'))]];$q=new WP_Query($args);return rest_ensure_response(['items'=>array_map([$this,'normalize'],$q->posts),'total'=>(int)$q->found_posts,'page'=>$page]);}
  public function song($r){$p=get_posts(['post_type'=>'song','name'=>sanitize_title($r['slug']),'post_status'=>'publish','numberposts'=>1]);return$p?rest_ensure_response($this->normalize($p[0])):new WP_Error('not_found','Song not found',['status'=>404]);}
  public function suggestions($r){$q=mb_substr(sanitize_text_field($r->get_param('q')?:''),0,120);if(mb_strlen($q)<2)return rest_ensure_response(['items'=>[]]);$items=array_slice($this->matching_posts($r),0,6);return rest_ensure_response(['items'=>array_map(function($s){return['id'=>$s['id'],'slug'=>$s['slug'],'title'=>$s['title'],'romanTitle'=>$s['romanTitle'],'artist'=>$s['artist'],'language'=>$s['language'],'matchType'=>$s['matchType'],'snippet'=>$s['snippet']];},$items)]);}
  public function search($r){$q=mb_substr(sanitize_text_field($r->get_param('q')?:''),0,120);if(!$q)return rest_ensure_response(['items'=>[],'total'=>0,'page'=>1]);$all=$this->matching_posts($r);$page=max(1,(int)($r->get_param('page')?:1));$per=min(50,max(1,(int)($r->get_param('per_page')?:20)));$items=array_slice($all,($page-1)*$per,$per);foreach($items as&$i)unset($i['_score']);return rest_ensure_response(['items'=>$items,'total'=>count($all),'page'=>$page,'per_page'=>$per]);}
  public function ads($r){if($r->get_method()==='PUT'){$v=$r->get_json_params();update_option('christian_lyrics_ads',is_array($v)?$v:[]);}return rest_ensure_response(get_option('christian_lyrics_ads',['global'=>false,'placements'=>[]]));}
  public function register_settings(){register_setting('elroi_tunes_settings','elroi_todo_api_token',['sanitize_callback'=>'sanitize_text_field']);}
  public function settings_menu(){add_options_page('Elroi Tunes Settings','Elroi Tunes','manage_options','elroi-tunes-settings',[$this,'settings_page']);}
  public function settings_page(){if(!current_user_can('manage_options'))return;echo '<div class="wrap"><h1>Elroi Tunes Settings</h1><form method="post" action="options.php">';settings_fields('elroi_tunes_settings');echo '<table class="form-table"><tr><th><label for="elroi_todo_api_token">Private Song Manager API token</label></th><td><input class="regular-text" type="password" id="elroi_todo_api_token" name="elroi_todo_api_token" value="'.esc_attr(get_option('elroi_todo_api_token','')).'" autocomplete="new-password"><p class="description">Use the same token as WORDPRESS_API_TOKEN in the Next.js environment.</p></td></tr></table>';submit_button('Save token');echo '</form></div>';}
  public function task_permission($request){$provided=trim((string)$request->get_header('X-Elroi-API-Token'));if(!$provided&&!empty($_SERVER['HTTP_X_ELROI_API_TOKEN']))$provided=trim(sanitize_text_field(wp_unslash($_SERVER['HTTP_X_ELROI_API_TOKEN'])));if(!$provided){$authorization=(string)$request->get_header('Authorization');if(preg_match('/^Bearer\s+(.+)$/i',$authorization,$matches))$provided=trim($matches[1]);}if(!$provided&&!empty($_SERVER['HTTP_AUTHORIZATION'])&&preg_match('/^Bearer\s+(.+)$/i',wp_unslash($_SERVER['HTTP_AUTHORIZATION']),$matches))$provided=trim($matches[1]);$stored=trim((string)get_option('elroi_todo_api_token',''));return $stored!==''&&$provided!==''&&strlen($stored)===strlen($provided)&&hash_equals($stored,$provided);}
  public function task_meta_box(){add_meta_box('elroi_song_task_details','Song task details',[$this,'render_task_meta_box'],'song_task','normal','high');}
  public function render_task_meta_box($post){wp_nonce_field('elroi_song_task_details','elroi_song_task_nonce');$get=function($key)use($post){return get_post_meta($post->ID,$key,true);};$language=$get('task_language')?:'hindi';$status=$get('task_status')?:'planned';$priority=$get('task_priority')?:'normal';echo '<p><label><strong>Language</strong></label><br><select name="task_language"><option value="hindi" '.selected($language,'hindi',false).'>Hindi</option><option value="nepali" '.selected($language,'nepali',false).'>Nepali</option><option value="english" '.selected($language,'english',false).'>English</option></select></p><p><label><strong>Status</strong></label><br><select name="task_status"><option value="planned" '.selected($status,'planned',false).'>Planned</option><option value="in-progress" '.selected($status,'in-progress',false).'>In progress</option><option value="ready" '.selected($status,'ready',false).'>Ready</option><option value="uploaded" '.selected($status,'uploaded',false).'>Uploaded</option></select></p><p><label><strong>Priority</strong></label><br><select name="task_priority"><option value="high" '.selected($priority,'high',false).'>High</option><option value="normal" '.selected($priority,'normal',false).'>Normal</option><option value="low" '.selected($priority,'low',false).'>Low</option></select></p><p><label><strong>Notes</strong></label><br><textarea name="task_notes" rows="5" style="width:100%">'.esc_textarea($get('task_notes')).'</textarea></p>';}
  public function save_task_meta($post_id,$post){if(!isset($_POST['elroi_song_task_nonce'])||!wp_verify_nonce(sanitize_text_field(wp_unslash($_POST['elroi_song_task_nonce'])),'elroi_song_task_details')||defined('DOING_AUTOSAVE')&&DOING_AUTOSAVE||!current_user_can('edit_post',$post_id)||$post->post_type!=='song_task')return;$lang=sanitize_key(wp_unslash($_POST['task_language']??'hindi'));$status=sanitize_key(wp_unslash($_POST['task_status']??'planned'));$priority=sanitize_key(wp_unslash($_POST['task_priority']??'normal'));if(!in_array($lang,['hindi','nepali','english'],true))$lang='hindi';if(!in_array($status,['planned','in-progress','ready','uploaded'],true))$status='planned';if(!in_array($priority,['high','normal','low'],true))$priority='normal';$this->save_task_values($post_id,['language'=>$lang,'status'=>$status,'priority'=>$priority,'notes'=>sanitize_textarea_field(wp_unslash($_POST['task_notes']??''))]);}
  private function task_data($post){return['id'=>$post->ID,'title'=>$post->post_title,'language'=>get_post_meta($post->ID,'task_language',true)?:'hindi','status'=>get_post_meta($post->ID,'task_status',true)?:'planned','priority'=>get_post_meta($post->ID,'task_priority',true)?:'normal','notes'=>get_post_meta($post->ID,'task_notes',true)?:'','createdAt'=>get_post_meta($post->ID,'task_created_at',true)?:$post->post_date_gmt,'updatedAt'=>get_post_meta($post->ID,'task_updated_at',true)?:$post->post_modified_gmt,'uploadedSongId'=>get_post_meta($post->ID,'task_uploaded_song_id',true)?:null,'uploadedSongSlug'=>get_post_meta($post->ID,'task_uploaded_song_slug',true)?:null,'uploadedAt'=>get_post_meta($post->ID,'task_uploaded_at',true)?:null];}
  private function save_task_values($id,$data){$now=gmdate('c');if(isset($data['title']))wp_update_post(['ID'=>$id,'post_title'=>sanitize_text_field($data['title'])]);$keys=['language'=>'task_language','status'=>'task_status','priority'=>'task_priority','notes'=>'task_notes','uploadedSongId'=>'task_uploaded_song_id','uploadedSongSlug'=>'task_uploaded_song_slug','uploadedAt'=>'task_uploaded_at'];foreach($keys as $field=>$key)if(array_key_exists($field,$data))update_post_meta($id,$key,$field==='notes'?sanitize_textarea_field((string)$data[$field]):sanitize_text_field((string)$data[$field]));if(!get_post_meta($id,'task_created_at',true))update_post_meta($id,'task_created_at',$now);update_post_meta($id,'task_updated_at',$now);}
  private function task_post($id){$post=get_post((int)$id);return $post&&$post->post_type==='song_task'&&$post->post_status!=='trash'?$post:null;}
  public function tasks($request){$posts=get_posts(['post_type'=>'song_task','post_status'=>['publish','draft','private'],'posts_per_page'=>-1,'orderby'=>'modified','order'=>'DESC']);return rest_ensure_response(['items'=>array_map([$this,'task_data'],$posts)]);}
  public function create_task($request){$body=(array)$request->get_json_params();$title=sanitize_text_field($body['title']??'');if(!$title)return new WP_Error('missing_title','Song title is required',['status'=>400]);$needle=$this->fold($title);foreach(get_posts(['post_type'=>'song_task','post_status'=>['publish','draft','private'],'posts_per_page'=>-1]) as $existing)if($this->fold($existing->post_title)===$needle)return new WP_Error('duplicate_task','This song is already on the task list',['status'=>409]);$id=wp_insert_post(['post_type'=>'song_task','post_status'=>'publish','post_title'=>$title],true);if(is_wp_error($id))return$id;$this->save_task_values($id,['language'=>$body['language']??'hindi','status'=>$body['status']??'planned','priority'=>$body['priority']??'normal','notes'=>$body['notes']??'','uploadedSongId'=>$body['uploadedSongId']??'','uploadedSongSlug'=>$body['uploadedSongSlug']??'','uploadedAt'=>$body['uploadedAt']??'']);return new WP_REST_Response($this->task_data(get_post($id)),201);}
  public function update_task($request){$post=$this->task_post($request['id']);if(!$post)return new WP_Error('not_found','Task not found',['status'=>404]);$body=(array)$request->get_json_params();$data=[];foreach(['title','language','status','priority','notes','uploadedSongId','uploadedSongSlug','uploadedAt'] as $field)if(array_key_exists($field,$body))$data[$field]=$body[$field];if(isset($data['title'])){ $needle=$this->fold($data['title']);foreach(get_posts(['post_type'=>'song_task','post_status'=>['publish','draft','private'],'posts_per_page'=>-1]) as $existing)if($existing->ID!==$post->ID&&$this->fold($existing->post_title)===$needle)return new WP_Error('duplicate_task','Another task already uses this title',['status'=>409]); }$this->save_task_values($post->ID,$data);return rest_ensure_response($this->task_data(get_post($post->ID)));}
  public function delete_task($request){$post=$this->task_post($request['id']);if(!$post)return new WP_Error('not_found','Task not found',['status'=>404]);wp_trash_post($post->ID);return rest_ensure_response(['ok'=>true,'id'=>$post->ID]);}
  public function activate(){flush_rewrite_rules();}
  public function validate($data,$postarr){if(($postarr['post_type']??'')==='song'&&($postarr['post_status']??'')==='publish'&&empty($postarr['post_title']))$data['post_status']='draft';return$data;}
  public function revalidate($id,$post,$update){if(wp_is_post_revision($id)||wp_is_post_autosave($id))return;$url=getenv('VERCEL_REVALIDATE_URL')?:getenv('SONGLIGHT_REVALIDATE_URL');$secret=getenv('WORDPRESS_WEBHOOK_SECRET')?:getenv('SONGLIGHT_REVALIDATE_SECRET');if(!$url||!$secret)return;wp_remote_post($url,['timeout'=>5,'blocking'=>false,'headers'=>['Content-Type'=>'application/json','X-Webhook-Secret'=>$secret],'body'=>wp_json_encode(['slug'=>$post->post_name,'status'=>$post->post_status,'language'=>get_post_meta($id,'language',true)])]);}
  private function admin_script(){return <<<'JS'
(function(){
  const o=document.getElementById('cla_original_lyrics'),r=document.getElementById('cla_roman_lyrics'),l=document.getElementById('cla_language'),b=document.getElementById('cla_generate'),s=document.getElementById('cla_generate_status'),h=document.getElementById('cla_lyrics'),n=document.getElementById('cla_ajax_nonce');
  if(!o||!r)return;
  const romanFallback=v=>v.replace(/\n\s*\n/g,'\n\n').trim();
  const parseSections=value=>{const lines=value.replace(/\\r\\n|\\n|\\r/g,'\n').split(/\n/),rows=[];let label='',body=[];const flush=()=>{const text=body.join('\n').trim();if(text||label)rows.push({label,original:text});label='';body=[];};lines.forEach(line=>{const match=line.match(/^\s*\[([^\]\n]+)\]\s*$/);if(match){flush();label=match[1].trim();}else body.push(line);});flush();return rows;};
  const sections=()=>{const a=parseSections(o.value),b=parseSections(r.value),count=Math.max(a.length,b.length);return Array.from({length:count},(_,i)=>({label:a[i]?.label||b[i]?.label||'Section '+(i+1),original:a[i]?.original||'',roman:b[i]?.original||''}));};
  async function convert(text,direction){const body=new URLSearchParams({action:'cla_transliterate',nonce:n?n.value:'',text,language:l.value,direction});const response=await fetch(window.ajaxurl,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});const data=await response.json();if(!data.success)throw new Error('conversion failed');return data.data.text;}
  async function make(){
    if(l.value==='english'){h.value=JSON.stringify(sections().map(x=>({label:x.label,original:x.original})));s.textContent='English lyrics are ready.';return;}
    try{b.disabled=true;if(!o.value.trim()&&r.value.trim()){s.textContent='Creating accurate Devanagari…';o.value=await convert(r.value,'to_native');}else if(!r.value.trim()&&o.value.trim()){s.textContent='Creating Roman lyrics…';r.value=await convert(o.value,'to_roman');}h.value=JSON.stringify(sections());s.textContent='Done — review both versions, then click Publish or Update.';}catch(e){s.textContent='Conversion could not be completed. Please try again or paste the missing version.';}finally{b.disabled=false;}
  }
  b.addEventListener('click',make);const form=document.getElementById('post');form.addEventListener('submit',async function(e){if(o.value.trim()||!r.value.trim())return;e.preventDefault();await make();form.submit();});
  try{const rows=JSON.parse(h.value||'[]');if(rows.length){o.value=rows.map(x=>(x.label?'['+x.label+']\n':'')+(x.original||x.text||'')).join('\n\n');r.value=rows.map(x=>(x.label?'['+x.label+']\n':'')+(x.roman||'')).join('\n\n')}}catch(e){}
})();
JS;}
  private function admin_style(){return '.cla-editor{background:#fbfcf9;border:1px solid #dfe8d8;border-radius:14px;padding:24px;margin:4px 0 10px}.cla-welcome{background:#eef5e9;border-left:4px solid #536b3b;padding:16px 18px;border-radius:8px;margin-bottom:22px}.cla-welcome strong,.cla-welcome span{display:block}.cla-welcome span{margin-top:5px;color:#66705f}.cla-grid,.cla-script-grid,.cla-advanced-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:20px}.cla-script-grid{gap:24px}.cla-label{display:block;font-weight:600;margin-bottom:8px;color:#263329}.cla-label span,.cla-advanced summary span{font-weight:400;color:#7b8575;font-size:12px}.cla-big-input{width:100%;box-sizing:border-box;border:1px solid #cdd9c6;border-radius:8px;padding:11px 13px;background:#fff;font-size:15px}.cla-big-input:focus,.cla-lyrics-input:focus{border-color:#536b3b;box-shadow:0 0 0 2px #536b3b22;outline:none}.cla-lyrics-input{width:100%;box-sizing:border-box;border:1px solid #cdd9c6;border-radius:8px;padding:14px;line-height:1.6;font-size:15px;resize:vertical}.cla-actions{display:flex;align-items:center;gap:14px;flex-wrap:wrap;margin:3px 0 24px}.cla-actions .button-primary{background:#536b3b;border-color:#536b3b}.cla-status{color:#66705f}.cla-advanced{border-top:1px solid #dfe8d8;padding-top:18px}.cla-advanced summary{cursor:pointer;font-size:15px;font-weight:600}.cla-wide{grid-column:1/-1}.cla-hidden{display:none}@media(max-width:782px){.cla-grid,.cla-script-grid,.cla-advanced-grid{grid-template-columns:1fr}.cla-editor{padding:16px}.cla-wide{grid-column:auto}}';}
}
new Christian_Lyrics_API();
